/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuadrantRouteImport } from './routes/quadrant'
import { Route as ShapeRouteImport } from './routes/shape'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuadrantRoute = QuadrantRouteImport.update({
  id: '/quadrant',
  path: '/quadrant',
  getParentRoute: () => rootRouteImport,
} as any)
const ShapeRoute = ShapeRouteImport.update({
  id: '/shape',
  path: '/shape',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quadrant': typeof QuadrantRoute
  '/shape': typeof ShapeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quadrant': typeof QuadrantRoute
  '/shape': typeof ShapeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quadrant': typeof QuadrantRoute
  '/shape': typeof ShapeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quadrant' | '/shape'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quadrant' | '/shape'
  id: '__root__' | '/' | '/quadrant' | '/shape'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuadrantRoute: typeof QuadrantRoute
  ShapeRoute: typeof ShapeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quadrant': {
      id: '/quadrant'
      path: '/quadrant'
      fullPath: '/quadrant'
      preLoaderRoute: typeof QuadrantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shape': {
      id: '/shape'
      path: '/shape'
      fullPath: '/shape'
      preLoaderRoute: typeof ShapeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuadrantRoute: QuadrantRoute,
  ShapeRoute: ShapeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
